name: DKPermsChatExtension
author: Davide Wietlisbach
description: 
version: ${project.version}
depend: [DKPerms]
api-version: 1.13

main: ch.dkrieger.permissionsystem.bukkit.tools.chat.ChatExtension

