name: DKPerms
author: Davide Wietlisbach
version: ${project.version}
api-version: 1.13
softdepend: [Vault, PlaceholderAPI]
loadbefore: [EZRanksPr]

main: ch.dkrieger.permissionsystem.bukkit.BukkitBootstrap
commands:
