name: DKPermsTabListExtension
author: Davide Wietlisbach
description: 
version: ${project.version}
api-version: 1.13

main: ch.dkrieger.permissionsystem.bukkit.tools.tablist.TabListExtension
commands:
