name: DKPermsTabListExtension
author: Davide Wietlisbach
version: ${project.version}
api-version: 1.13
softdepend: [PlaceHolderAPI]

main: ch.dkrieger.permissionsystem.bukkit.tools.tablist.TabListExtension
