name: DKPermsRankChangeMessage
author: Davide Wietlisbach
description: 
version: ${project.version}
api-version: 1.13
depend: [DKPerms]

main: ch.dkrieger.permissionsystem.tools.rankchangemessage.bukkit.BukkitRankChangeMessageExtension
commands:
