name: DKPermsDKBansConnection
author: Dkrieger
description: 
version: ${project.version}
api-version: 1.13

main: ch.dkrieger.permissionsystem.tools.dkbansconnection.bukkit.BukkitDKPermsDKBansConnection
commands:
