name: DKPermsRankChangeCommand
author: Davide Wietlisbach
description: 
version: ${project.version}
api-version: 1.13
depend: [DKPerms]

main: ch.dkrieger.permissionsystem.rankchangecommand.bukkit.BukkitCordRankChangeCommandExtension
commands:
