name: DKPermsDKCoinsConnection
author: Davide Wietlisbach
version: ${project.version}
api-version: 1.13
depend: [DKPerms, DKCoins]

main: ch.dkrieger.permissionsystem.tools.dkcoinsconnection.bukkit.BukkitDKPermsDKCoinsConnection